name: sklearn-env

# These should be 1-1 with environments/dev.txt
dependencies:
    - pytest
    - pytest-cov
    - flake8
    - mypy
    - numpydoc
    - black=22.3.0
    - pre-commit
channels:
    - conda-forge
    - anaconda
